/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica8_LienzoImagen2D;

import sm.prg.iu.Herramientas;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Stroke;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;

/**
 *
 * @author Shiri
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form ventanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }
    
    public VentanaInterna seleccionVentana(){
        VentanaInterna vi;
        vi = (VentanaInterna)escritorio.getSelectedFrame();
        return vi; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        colores = new javax.swing.ButtonGroup();
        formas = new javax.swing.ButtonGroup();
        barraAtributos = new javax.swing.JPanel();
        etiqueta = new javax.swing.JLabel();
        atributos = new javax.swing.JPanel();
        panelColores = new javax.swing.JPanel();
        tablaColores = new javax.swing.JPanel();
        colores1 = new javax.swing.JPanel();
        negro = new javax.swing.JToggleButton();
        rojo = new javax.swing.JToggleButton();
        azul = new javax.swing.JToggleButton();
        colores2 = new javax.swing.JPanel();
        blanco = new javax.swing.JToggleButton();
        amarillo = new javax.swing.JToggleButton();
        verde = new javax.swing.JToggleButton();
        color_texto = new java.awt.Label();
        panelGrosor = new javax.swing.JPanel();
        grosor_texto = new java.awt.Label();
        grosor = new javax.swing.JPanel();
        tamGrosor = new javax.swing.JSpinner();
        panelAtributos = new javax.swing.JPanel();
        atributos1 = new javax.swing.JPanel();
        relleno = new javax.swing.JCheckBox();
        alisar = new javax.swing.JCheckBox();
        atributos2 = new javax.swing.JPanel();
        transparencia = new javax.swing.JCheckBox();
        editar = new javax.swing.JCheckBox();
        barraHerramientas = new javax.swing.JToolBar();
        punto = new javax.swing.JToggleButton();
        linea = new javax.swing.JToggleButton();
        rectangulo = new javax.swing.JToggleButton();
        elipse = new javax.swing.JToggleButton();
        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        Archivo = new javax.swing.JMenu();
        Nuevo = new javax.swing.JMenuItem();
        Abrir = new javax.swing.JMenuItem();
        Guardar = new javax.swing.JMenuItem();
        Edicion = new javax.swing.JMenu();
        verBarraEstado = new javax.swing.JCheckBoxMenuItem();
        verBarraFormas = new javax.swing.JCheckBoxMenuItem();
        verBarraAtributos = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        barraAtributos.setLayout(new java.awt.BorderLayout());

        etiqueta.setText("Elige una herramienta.");
        barraAtributos.add(etiqueta, java.awt.BorderLayout.PAGE_END);

        atributos.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        panelColores.setLayout(new java.awt.BorderLayout());

        tablaColores.setLayout(new java.awt.BorderLayout());

        negro.setBackground(java.awt.Color.black);
        colores.add(negro);
        negro.setPreferredSize(new java.awt.Dimension(20, 20));
        negro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negroActionPerformed(evt);
            }
        });
        colores1.add(negro);

        rojo.setBackground(java.awt.Color.red);
        colores.add(rojo);
        rojo.setPreferredSize(new java.awt.Dimension(20, 20));
        rojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rojoActionPerformed(evt);
            }
        });
        colores1.add(rojo);

        azul.setBackground(java.awt.Color.blue);
        colores.add(azul);
        azul.setPreferredSize(new java.awt.Dimension(20, 20));
        azul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                azulActionPerformed(evt);
            }
        });
        colores1.add(azul);

        tablaColores.add(colores1, java.awt.BorderLayout.PAGE_START);

        blanco.setBackground(java.awt.Color.white);
        colores.add(blanco);
        blanco.setPreferredSize(new java.awt.Dimension(20, 20));
        blanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blancoActionPerformed(evt);
            }
        });
        colores2.add(blanco);

        amarillo.setBackground(java.awt.Color.yellow);
        colores.add(amarillo);
        amarillo.setPreferredSize(new java.awt.Dimension(20, 20));
        amarillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amarilloActionPerformed(evt);
            }
        });
        colores2.add(amarillo);

        verde.setBackground(java.awt.Color.green);
        colores.add(verde);
        verde.setPreferredSize(new java.awt.Dimension(20, 20));
        verde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verdeActionPerformed(evt);
            }
        });
        colores2.add(verde);

        tablaColores.add(colores2, java.awt.BorderLayout.PAGE_END);

        panelColores.add(tablaColores, java.awt.BorderLayout.PAGE_END);

        color_texto.setText("Color");
        panelColores.add(color_texto, java.awt.BorderLayout.PAGE_START);

        atributos.add(panelColores);

        panelGrosor.setLayout(new java.awt.BorderLayout());

        grosor_texto.setText("Grosor");
        panelGrosor.add(grosor_texto, java.awt.BorderLayout.PAGE_START);

        tamGrosor.setPreferredSize(new java.awt.Dimension(39, 30));
        tamGrosor.setValue(1);
        tamGrosor.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tamGrosorStateChanged(evt);
            }
        });
        grosor.add(tamGrosor);

        panelGrosor.add(grosor, java.awt.BorderLayout.CENTER);

        atributos.add(panelGrosor);

        panelAtributos.setLayout(new java.awt.BorderLayout());

        atributos1.setLayout(new java.awt.BorderLayout());

        relleno.setText("Relleno");
        relleno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rellenoActionPerformed(evt);
            }
        });
        atributos1.add(relleno, java.awt.BorderLayout.PAGE_START);

        alisar.setText("Alisar");
        alisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alisarActionPerformed(evt);
            }
        });
        atributos1.add(alisar, java.awt.BorderLayout.PAGE_END);

        panelAtributos.add(atributos1, java.awt.BorderLayout.LINE_START);

        atributos2.setLayout(new java.awt.BorderLayout());

        transparencia.setText("Transparencia");
        transparencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transparenciaActionPerformed(evt);
            }
        });
        atributos2.add(transparencia, java.awt.BorderLayout.PAGE_START);

        editar.setText("Editar");
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });
        atributos2.add(editar, java.awt.BorderLayout.PAGE_END);

        panelAtributos.add(atributos2, java.awt.BorderLayout.LINE_END);

        atributos.add(panelAtributos);

        barraAtributos.add(atributos, java.awt.BorderLayout.CENTER);

        getContentPane().add(barraAtributos, java.awt.BorderLayout.PAGE_END);

        barraHerramientas.setRollover(true);

        formas.add(punto);
        punto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica8_LienzoImagen2D/iconos/punto.png"))); // NOI18N
        punto.setFocusable(false);
        punto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        punto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        punto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puntoActionPerformed(evt);
            }
        });
        barraHerramientas.add(punto);

        formas.add(linea);
        linea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica8_LienzoImagen2D/iconos/linea.png"))); // NOI18N
        linea.setFocusable(false);
        linea.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        linea.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        linea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lineaActionPerformed(evt);
            }
        });
        barraHerramientas.add(linea);

        formas.add(rectangulo);
        rectangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica8_LienzoImagen2D/iconos/rectangulo.png"))); // NOI18N
        rectangulo.setFocusable(false);
        rectangulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rectangulo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        rectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rectanguloActionPerformed(evt);
            }
        });
        barraHerramientas.add(rectangulo);

        formas.add(elipse);
        elipse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica8_LienzoImagen2D/iconos/elipse.png"))); // NOI18N
        elipse.setFocusable(false);
        elipse.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        elipse.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        elipse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elipseActionPerformed(evt);
            }
        });
        barraHerramientas.add(elipse);

        getContentPane().add(barraHerramientas, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 142, Short.MAX_VALUE)
        );

        getContentPane().add(escritorio, java.awt.BorderLayout.CENTER);

        Archivo.setText("Archivo");

        Nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica8_LienzoImagen2D/iconos/nuevo.png"))); // NOI18N
        Nuevo.setText("Nuevo");
        Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoActionPerformed(evt);
            }
        });
        Archivo.add(Nuevo);

        Abrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica8_LienzoImagen2D/iconos/abrir.png"))); // NOI18N
        Abrir.setText("Abrir");
        Abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirActionPerformed(evt);
            }
        });
        Archivo.add(Abrir);

        Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica8_LienzoImagen2D/iconos/guardar.png"))); // NOI18N
        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        Archivo.add(Guardar);

        jMenuBar1.add(Archivo);

        Edicion.setText("Edicion");

        verBarraEstado.setSelected(true);
        verBarraEstado.setText("Ver barra de estado");
        verBarraEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verBarraEstadoActionPerformed(evt);
            }
        });
        Edicion.add(verBarraEstado);

        verBarraFormas.setSelected(true);
        verBarraFormas.setText("Ver barra de formas");
        verBarraFormas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verBarraFormasActionPerformed(evt);
            }
        });
        Edicion.add(verBarraFormas);

        verBarraAtributos.setSelected(true);
        verBarraAtributos.setText("Ver barra de atributos");
        verBarraAtributos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verBarraAtributosActionPerformed(evt);
            }
        });
        Edicion.add(verBarraAtributos);

        jMenuBar1.add(Edicion);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoActionPerformed
       VentanaInterna vi = new VentanaInterna();
       escritorio.add(vi);
       vi.setVisible(true);
       //punto.doClick();
       BufferedImage img;
       img = new BufferedImage(300,300,BufferedImage.TYPE_INT_RGB);
       vi.getLienzo().setImage(img);
    }//GEN-LAST:event_NuevoActionPerformed

    private void lineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lineaActionPerformed
        seleccionVentana().getLienzo().setForma(Herramientas.linea);
        etiqueta.setText("Linea.");
    }//GEN-LAST:event_lineaActionPerformed

    private void rectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rectanguloActionPerformed
        seleccionVentana().getLienzo().setForma(Herramientas.rectangulo);
        etiqueta.setText("Rectangulo.");
    }//GEN-LAST:event_rectanguloActionPerformed

    private void elipseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elipseActionPerformed
        seleccionVentana().getLienzo().setForma(Herramientas.elipse);
        etiqueta.setText("Elipse.");
    }//GEN-LAST:event_elipseActionPerformed

    private void puntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puntoActionPerformed
       seleccionVentana().getLienzo().setForma(Herramientas.punto);
       etiqueta.setText("Punto.");
    }//GEN-LAST:event_puntoActionPerformed

    private void tamGrosorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tamGrosorStateChanged
        Stroke nuevo = new BasicStroke((int)tamGrosor.getValue()); 
        seleccionVentana().getLienzo().setStroke(nuevo); 
    }//GEN-LAST:event_tamGrosorStateChanged

    private void rellenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rellenoActionPerformed
        if (relleno.isSelected()){
            seleccionVentana().getLienzo().setRelleno(true);
        }
        else{
            seleccionVentana().getLienzo().setRelleno(false);
        }
    }//GEN-LAST:event_rellenoActionPerformed

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        if (editar.isSelected()){
            seleccionVentana().getLienzo().setEditar(true);
        }
        else{
            seleccionVentana().getLienzo().setEditar(false);
        }
    }//GEN-LAST:event_editarActionPerformed

    private void negroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negroActionPerformed
        seleccionVentana().getLienzo().setColor(Color.black);
    }//GEN-LAST:event_negroActionPerformed

    private void rojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rojoActionPerformed
        seleccionVentana().getLienzo().setColor(Color.red);
    }//GEN-LAST:event_rojoActionPerformed

    private void azulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_azulActionPerformed
        seleccionVentana().getLienzo().setColor(Color.blue);
    }//GEN-LAST:event_azulActionPerformed

    private void blancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blancoActionPerformed
        seleccionVentana().getLienzo().setColor(Color.white);
    }//GEN-LAST:event_blancoActionPerformed

    private void amarilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amarilloActionPerformed
        seleccionVentana().getLienzo().setColor(Color.yellow);
    }//GEN-LAST:event_amarilloActionPerformed

    private void verdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verdeActionPerformed
        seleccionVentana().getLienzo().setColor(Color.green);
    }//GEN-LAST:event_verdeActionPerformed

    private void AbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirActionPerformed
        JFileChooser dlg = new JFileChooser();
        int resp = dlg.showOpenDialog(this);
        if( resp == JFileChooser.APPROVE_OPTION) {
            try{
                File f = dlg.getSelectedFile();
                BufferedImage img = ImageIO.read(f);
                VentanaInterna vi = new VentanaInterna();
                vi.getLienzo().setImage(img);
                this.escritorio.add(vi);
                vi.setTitle(f.getName());
                vi.setVisible(true);
            }catch(Exception ex){
                System.err.println("Error al leer la imagen");
            }
        }
    }//GEN-LAST:event_AbrirActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        VentanaInterna vi=(VentanaInterna) escritorio.getSelectedFrame();
        if (vi != null) {
            JFileChooser dlg = new JFileChooser();
            int resp = dlg.showSaveDialog(this);
                if (resp == JFileChooser.APPROVE_OPTION) {
                try {
                    BufferedImage img = vi.getLienzo().getImage(true);
                    if (img != null) {
                        File f = dlg.getSelectedFile();
                        ImageIO.write(img, "jpg", f);
                        vi.setTitle(f.getName());
                    }
                }catch (Exception ex) {
                    System.err.println("Error al guardar la imagen");
                }
            }
        }
    }//GEN-LAST:event_GuardarActionPerformed

    private void transparenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transparenciaActionPerformed
        if (transparencia.isSelected()){
            seleccionVentana().getLienzo().setTransparencia(true);
        }
        else{
            seleccionVentana().getLienzo().setTransparencia(false);
        }
    }//GEN-LAST:event_transparenciaActionPerformed

    private void alisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alisarActionPerformed
        if (alisar.isSelected()){
            seleccionVentana().getLienzo().setAlisar(true);
        }
        else{
            seleccionVentana().getLienzo().setAlisar(false);
        }
    }//GEN-LAST:event_alisarActionPerformed

    private void verBarraEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verBarraEstadoActionPerformed
        if(verBarraEstado.isSelected()){
            this.etiqueta.setVisible(true);
        }
        else{
            this.etiqueta.setVisible(false);
        }
    }//GEN-LAST:event_verBarraEstadoActionPerformed

    private void verBarraFormasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verBarraFormasActionPerformed
        if(verBarraFormas.isSelected()){
            this.barraHerramientas.setVisible(true);
        }
        else{
            this.barraHerramientas.setVisible(false);
        }
    }//GEN-LAST:event_verBarraFormasActionPerformed

    private void verBarraAtributosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verBarraAtributosActionPerformed
        if(verBarraAtributos.isSelected()){
            this.atributos.setVisible(true);
        }
        else{
            this.atributos.setVisible(false);
        }
    }//GEN-LAST:event_verBarraAtributosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Abrir;
    private javax.swing.JMenu Archivo;
    private javax.swing.JMenu Edicion;
    private javax.swing.JMenuItem Guardar;
    private javax.swing.JMenuItem Nuevo;
    private javax.swing.JCheckBox alisar;
    private javax.swing.JToggleButton amarillo;
    private javax.swing.JPanel atributos;
    private javax.swing.JPanel atributos1;
    private javax.swing.JPanel atributos2;
    private javax.swing.JToggleButton azul;
    private javax.swing.JPanel barraAtributos;
    private javax.swing.JToolBar barraHerramientas;
    private javax.swing.JToggleButton blanco;
    private java.awt.Label color_texto;
    private javax.swing.ButtonGroup colores;
    private javax.swing.JPanel colores1;
    private javax.swing.JPanel colores2;
    private javax.swing.JCheckBox editar;
    private javax.swing.JToggleButton elipse;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel etiqueta;
    private javax.swing.ButtonGroup formas;
    private javax.swing.JPanel grosor;
    private java.awt.Label grosor_texto;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToggleButton linea;
    private javax.swing.JToggleButton negro;
    private javax.swing.JPanel panelAtributos;
    private javax.swing.JPanel panelColores;
    private javax.swing.JPanel panelGrosor;
    private javax.swing.JToggleButton punto;
    private javax.swing.JToggleButton rectangulo;
    private javax.swing.JCheckBox relleno;
    private javax.swing.JToggleButton rojo;
    private javax.swing.JPanel tablaColores;
    private javax.swing.JSpinner tamGrosor;
    private javax.swing.JCheckBox transparencia;
    private javax.swing.JCheckBoxMenuItem verBarraAtributos;
    private javax.swing.JCheckBoxMenuItem verBarraEstado;
    private javax.swing.JCheckBoxMenuItem verBarraFormas;
    private javax.swing.JToggleButton verde;
    // End of variables declaration//GEN-END:variables
}
