/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica7b_paint2d;

import sm.prg.iu.Herramientas;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Stroke;
import java.awt.image.BufferedImage;
import java.awt.image.ColorModel;
import java.awt.image.ConvolveOp;
import java.awt.image.Kernel;
import java.awt.image.RescaleOp;
import java.awt.image.WritableRaster;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import sm.image.KernelProducer;

/**
 *
 * @author Shiri
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private BufferedImage imgSource;

    /**
     * Creates new form ventanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }
    
    public VentanaInterna seleccionVentana(){
        VentanaInterna vi;
        vi = (VentanaInterna)escritorio.getSelectedFrame();
        return vi; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        colores = new javax.swing.ButtonGroup();
        formas = new javax.swing.ButtonGroup();
        atributos = new javax.swing.JPanel();
        etiqueta = new javax.swing.JLabel();
        herramientasImagenes = new javax.swing.JToolBar();
        brillibrilli = new javax.swing.JPanel();
        sliderBrillo = new javax.swing.JSlider();
        filtrito = new javax.swing.JPanel();
        comboFiltros = new javax.swing.JComboBox<>();
        constrati = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        barraHerramientas = new javax.swing.JToolBar();
        punto = new javax.swing.JToggleButton();
        linea = new javax.swing.JToggleButton();
        rectangulo = new javax.swing.JToggleButton();
        elipse = new javax.swing.JToggleButton();
        selecion = new javax.swing.JToggleButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        tamGrosor = new javax.swing.JSpinner();
        relleno = new javax.swing.JToggleButton();
        transparencia = new javax.swing.JToggleButton();
        alisar = new javax.swing.JToggleButton();
        colores2 = new javax.swing.JPanel();
        blanco = new javax.swing.JToggleButton();
        amarillo = new javax.swing.JToggleButton();
        verde = new javax.swing.JToggleButton();
        azul = new javax.swing.JToggleButton();
        negro = new javax.swing.JToggleButton();
        rojo = new javax.swing.JToggleButton();
        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        Archivo = new javax.swing.JMenu();
        Nuevo = new javax.swing.JMenuItem();
        Abrir = new javax.swing.JMenuItem();
        Guardar = new javax.swing.JMenuItem();
        Edicion = new javax.swing.JMenu();
        verBarraEstado = new javax.swing.JCheckBoxMenuItem();
        verBarraFormas = new javax.swing.JCheckBoxMenuItem();
        verBarraAtributos = new javax.swing.JCheckBoxMenuItem();
        Imagen = new javax.swing.JMenu();
        RescaleOp = new javax.swing.JMenuItem();
        filtrosConvolve = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        atributos.setLayout(new java.awt.BorderLayout());

        etiqueta.setText("Elige una herramienta.");
        atributos.add(etiqueta, java.awt.BorderLayout.PAGE_END);

        herramientasImagenes.setRollover(true);

        sliderBrillo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sliderBrillo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderBrilloStateChanged(evt);
            }
        });
        sliderBrillo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                sliderBrilloFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                sliderBrilloFocusLost(evt);
            }
        });
        brillibrilli.add(sliderBrillo);

        herramientasImagenes.add(brillibrilli);

        comboFiltros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Media", "Binomial", "Enfoque", "Relieve", "Fronteras" }));
        comboFiltros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFiltrosActionPerformed(evt);
            }
        });
        filtrito.add(comboFiltros);

        herramientasImagenes.add(filtrito);

        jButton1.setText("jButton1");
        constrati.add(jButton1);

        jButton2.setText("jButton2");
        constrati.add(jButton2);

        jButton3.setText("jButton3");
        constrati.add(jButton3);

        herramientasImagenes.add(constrati);

        atributos.add(herramientasImagenes, java.awt.BorderLayout.CENTER);

        getContentPane().add(atributos, java.awt.BorderLayout.PAGE_END);

        barraHerramientas.setRollover(true);

        formas.add(punto);
        punto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica7b_paint2d/iconos/punto.png"))); // NOI18N
        punto.setFocusable(false);
        punto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        punto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        punto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puntoActionPerformed(evt);
            }
        });
        barraHerramientas.add(punto);

        formas.add(linea);
        linea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica7b_paint2d/iconos/linea.png"))); // NOI18N
        linea.setFocusable(false);
        linea.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        linea.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        linea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lineaActionPerformed(evt);
            }
        });
        barraHerramientas.add(linea);

        formas.add(rectangulo);
        rectangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica7b_paint2d/iconos/rectangulo.png"))); // NOI18N
        rectangulo.setFocusable(false);
        rectangulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rectangulo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        rectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rectanguloActionPerformed(evt);
            }
        });
        barraHerramientas.add(rectangulo);

        formas.add(elipse);
        elipse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica7b_paint2d/iconos/elipse.png"))); // NOI18N
        elipse.setFocusable(false);
        elipse.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        elipse.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        elipse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elipseActionPerformed(evt);
            }
        });
        barraHerramientas.add(elipse);

        selecion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica7b_paint2d/iconos/seleccion.png"))); // NOI18N
        selecion.setFocusable(false);
        selecion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        selecion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        selecion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionActionPerformed(evt);
            }
        });
        barraHerramientas.add(selecion);
        barraHerramientas.add(jSeparator1);

        tamGrosor.setMaximumSize(new java.awt.Dimension(29, 20));
        tamGrosor.setValue(1);
        tamGrosor.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tamGrosorStateChanged(evt);
            }
        });
        barraHerramientas.add(tamGrosor);

        relleno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica7b_paint2d/iconos/rellenar.png"))); // NOI18N
        relleno.setFocusable(false);
        relleno.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        relleno.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        relleno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rellenoActionPerformed(evt);
            }
        });
        barraHerramientas.add(relleno);

        transparencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica7b_paint2d/iconos/transparencia.png"))); // NOI18N
        transparencia.setFocusable(false);
        transparencia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        transparencia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        transparencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transparenciaActionPerformed(evt);
            }
        });
        barraHerramientas.add(transparencia);

        alisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica7b_paint2d/iconos/alisar.png"))); // NOI18N
        alisar.setFocusable(false);
        alisar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        alisar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        alisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alisarActionPerformed(evt);
            }
        });
        barraHerramientas.add(alisar);

        blanco.setBackground(java.awt.Color.white);
        colores.add(blanco);
        blanco.setPreferredSize(new java.awt.Dimension(20, 20));
        blanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blancoActionPerformed(evt);
            }
        });
        colores2.add(blanco);

        amarillo.setBackground(java.awt.Color.yellow);
        colores.add(amarillo);
        amarillo.setPreferredSize(new java.awt.Dimension(20, 20));
        amarillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amarilloActionPerformed(evt);
            }
        });
        colores2.add(amarillo);

        verde.setBackground(java.awt.Color.green);
        colores.add(verde);
        verde.setPreferredSize(new java.awt.Dimension(20, 20));
        verde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verdeActionPerformed(evt);
            }
        });
        colores2.add(verde);

        azul.setBackground(java.awt.Color.blue);
        colores.add(azul);
        azul.setPreferredSize(new java.awt.Dimension(20, 20));
        azul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                azulActionPerformed(evt);
            }
        });
        colores2.add(azul);

        negro.setBackground(java.awt.Color.black);
        colores.add(negro);
        negro.setPreferredSize(new java.awt.Dimension(20, 20));
        negro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negroActionPerformed(evt);
            }
        });
        colores2.add(negro);

        rojo.setBackground(java.awt.Color.red);
        colores.add(rojo);
        rojo.setPreferredSize(new java.awt.Dimension(20, 20));
        rojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rojoActionPerformed(evt);
            }
        });
        colores2.add(rojo);

        barraHerramientas.add(colores2);

        getContentPane().add(barraHerramientas, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 232, Short.MAX_VALUE)
        );

        getContentPane().add(escritorio, java.awt.BorderLayout.CENTER);

        Archivo.setText("Archivo");

        Nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica7b_paint2d/iconos/nuevo.png"))); // NOI18N
        Nuevo.setText("Nuevo");
        Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoActionPerformed(evt);
            }
        });
        Archivo.add(Nuevo);

        Abrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica7b_paint2d/iconos/abrir.png"))); // NOI18N
        Abrir.setText("Abrir");
        Abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirActionPerformed(evt);
            }
        });
        Archivo.add(Abrir);

        Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica7b_paint2d/iconos/guardar.png"))); // NOI18N
        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        Archivo.add(Guardar);

        jMenuBar1.add(Archivo);

        Edicion.setText("Edicion");

        verBarraEstado.setSelected(true);
        verBarraEstado.setText("Ver barra de estado");
        verBarraEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verBarraEstadoActionPerformed(evt);
            }
        });
        Edicion.add(verBarraEstado);

        verBarraFormas.setSelected(true);
        verBarraFormas.setText("Ver barra de formas");
        verBarraFormas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verBarraFormasActionPerformed(evt);
            }
        });
        Edicion.add(verBarraFormas);

        verBarraAtributos.setSelected(true);
        verBarraAtributos.setText("Ver barra de atributos");
        verBarraAtributos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verBarraAtributosActionPerformed(evt);
            }
        });
        Edicion.add(verBarraAtributos);

        jMenuBar1.add(Edicion);

        Imagen.setText("Imagen");

        RescaleOp.setText("RescaleOp");
        RescaleOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RescaleOpActionPerformed(evt);
            }
        });
        Imagen.add(RescaleOp);

        filtrosConvolve.setText("ConvolveOp");
        filtrosConvolve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtrosConvolveActionPerformed(evt);
            }
        });
        Imagen.add(filtrosConvolve);

        jMenuBar1.add(Imagen);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoActionPerformed
       VentanaInterna vi = new VentanaInterna();
       escritorio.add(vi);
       vi.setVisible(true);
       BufferedImage img;
       img = new BufferedImage(300,300,BufferedImage.TYPE_INT_RGB);
       vi.getLienzo().setImage(img);
    }//GEN-LAST:event_NuevoActionPerformed

    private void negroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negroActionPerformed
        seleccionVentana().getLienzo().setColor(Color.black);
    }//GEN-LAST:event_negroActionPerformed

    private void rojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rojoActionPerformed
        seleccionVentana().getLienzo().setColor(Color.red);
    }//GEN-LAST:event_rojoActionPerformed

    private void azulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_azulActionPerformed
        seleccionVentana().getLienzo().setColor(Color.blue);
    }//GEN-LAST:event_azulActionPerformed

    private void blancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blancoActionPerformed
        seleccionVentana().getLienzo().setColor(Color.white);
    }//GEN-LAST:event_blancoActionPerformed

    private void amarilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amarilloActionPerformed
        seleccionVentana().getLienzo().setColor(Color.yellow);
    }//GEN-LAST:event_amarilloActionPerformed

    private void verdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verdeActionPerformed
        seleccionVentana().getLienzo().setColor(Color.green);
    }//GEN-LAST:event_verdeActionPerformed

    private void AbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirActionPerformed
        JFileChooser dlg = new JFileChooser();
        int resp = dlg.showOpenDialog(this);
        if( resp == JFileChooser.APPROVE_OPTION) {
            try{
                File f = dlg.getSelectedFile();
                BufferedImage img = ImageIO.read(f);
                VentanaInterna vi = new VentanaInterna();
                vi.getLienzo().setImage(img);
                this.escritorio.add(vi);
                vi.setTitle(f.getName());
                vi.setVisible(true);
            }catch(Exception ex){
                System.err.println("Error al leer la imagen");
            }
        }
    }//GEN-LAST:event_AbrirActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        VentanaInterna vi=(VentanaInterna) escritorio.getSelectedFrame();
        if (vi != null) {
            JFileChooser dlg = new JFileChooser();
            int resp = dlg.showSaveDialog(this);
                if (resp == JFileChooser.APPROVE_OPTION) {
                try {
                    BufferedImage img = vi.getLienzo().getImage(true);
                    if (img != null) {
                        File f = dlg.getSelectedFile();
                        ImageIO.write(img, "jpg", f);
                        vi.setTitle(f.getName());
                    }
                }catch (Exception ex) {
                    System.err.println("Error al guardar la imagen");
                }
            }
        }
    }//GEN-LAST:event_GuardarActionPerformed

    private void verBarraEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verBarraEstadoActionPerformed
        if(verBarraEstado.isSelected()){
            this.etiqueta.setVisible(true);
        }
        else{
            this.etiqueta.setVisible(false);
        }
    }//GEN-LAST:event_verBarraEstadoActionPerformed

    private void verBarraFormasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verBarraFormasActionPerformed
        if(verBarraFormas.isSelected()){
            this.barraHerramientas.setVisible(true);
        }
        else{
            this.barraHerramientas.setVisible(false);
        }
    }//GEN-LAST:event_verBarraFormasActionPerformed

    private void verBarraAtributosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verBarraAtributosActionPerformed
        if(verBarraAtributos.isSelected()){
            this.atributos.setVisible(true);
        }
        else{
            this.atributos.setVisible(false);
        }
    }//GEN-LAST:event_verBarraAtributosActionPerformed

    private void alisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alisarActionPerformed
        if (alisar.isSelected()){
            seleccionVentana().getLienzo().setAlisar(true);
        }
        else{
            seleccionVentana().getLienzo().setAlisar(false);
        }
    }//GEN-LAST:event_alisarActionPerformed

    private void transparenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transparenciaActionPerformed
        if (transparencia.isSelected()){
            seleccionVentana().getLienzo().setTransparencia(true);
        }
        else{
            seleccionVentana().getLienzo().setTransparencia(false);
        }
    }//GEN-LAST:event_transparenciaActionPerformed

    private void rellenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rellenoActionPerformed
        if (relleno.isSelected()){
            seleccionVentana().getLienzo().setRelleno(true);
        }
        else{
            seleccionVentana().getLienzo().setRelleno(false);
        }
    }//GEN-LAST:event_rellenoActionPerformed

    private void tamGrosorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tamGrosorStateChanged
        Stroke nuevo = new BasicStroke((int)tamGrosor.getValue());
        seleccionVentana().getLienzo().setStroke(nuevo);
    }//GEN-LAST:event_tamGrosorStateChanged

    private void selecionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionActionPerformed
        if (selecion.isSelected()){
            seleccionVentana().getLienzo().setEditar(true);
        }
        else{
            seleccionVentana().getLienzo().setEditar(false);
        }
    }//GEN-LAST:event_selecionActionPerformed

    private void elipseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elipseActionPerformed
        seleccionVentana().getLienzo().setForma(Herramientas.elipse);
        etiqueta.setText("Elipse.");
    }//GEN-LAST:event_elipseActionPerformed

    private void rectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rectanguloActionPerformed
        seleccionVentana().getLienzo().setForma(Herramientas.rectangulo);
        etiqueta.setText("Rectangulo.");
    }//GEN-LAST:event_rectanguloActionPerformed

    private void lineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lineaActionPerformed
        seleccionVentana().getLienzo().setForma(Herramientas.linea);
        etiqueta.setText("Linea.");
    }//GEN-LAST:event_lineaActionPerformed

    private void puntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puntoActionPerformed
        seleccionVentana().getLienzo().setForma(Herramientas.punto);
        etiqueta.setText("Punto.");
    }//GEN-LAST:event_puntoActionPerformed

    private void RescaleOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RescaleOpActionPerformed
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            imgSource = vi.getLienzo().getImage(true);
            if(imgSource!=null){
                try{
                    RescaleOp rop = new RescaleOp(1.0F, 100.0F, null);
                    BufferedImage imgdest = rop.filter(imgSource, vi.getLienzo().getImage());
                    vi.getLienzo().setImage(imgdest);
                    vi.getLienzo().repaint();
                } catch(IllegalArgumentException e){
                    System.err.println(e.getLocalizedMessage());
                }
            }
        }
    }//GEN-LAST:event_RescaleOpActionPerformed

    private void filtrosConvolveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtrosConvolveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filtrosConvolveActionPerformed

    private void sliderBrilloFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sliderBrilloFocusGained
        VentanaInterna vi = (VentanaInterna)(escritorio.getSelectedFrame());
        if(vi!=null){
            ColorModel cm = vi.getLienzo().getImage().getColorModel();
            WritableRaster raster = vi.getLienzo().getImage().copyData(null);
            boolean alfaPre = vi.getLienzo().getImage().isAlphaPremultiplied();
            imgSource = new BufferedImage(cm,raster,alfaPre,null);
        }
    }//GEN-LAST:event_sliderBrilloFocusGained

    private void sliderBrilloFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sliderBrilloFocusLost
        imgSource = null;
        sliderBrillo.setValue(0);
    }//GEN-LAST:event_sliderBrilloFocusLost

    private void sliderBrilloStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderBrilloStateChanged
        VentanaInterna vi = (VentanaInterna)(escritorio.getSelectedFrame());
        BufferedImage img = vi.getLienzo().getImage();
           
        if(img!=null && imgSource != null){
            try{
                RescaleOp rop;           
                if(imgSource.getColorModel().hasAlpha()){
                    float[] factorEscala = {1.0F,1.0F,1.0F,1.0F};
                    float[] offSet = {sliderBrillo.getValue(), sliderBrillo.getValue(), sliderBrillo.getValue(), 0.0F};
                    rop = new RescaleOp(factorEscala, offSet, null);
                }
                else
                    rop = new RescaleOp(1.0F, sliderBrillo.getValue(), null);
                    rop.filter(imgSource, img);
                    escritorio.repaint();
            } catch(IllegalArgumentException e){
                System.err.println(e.getLocalizedMessage());
            }
        }
    }//GEN-LAST:event_sliderBrilloStateChanged

    private void comboFiltrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFiltrosActionPerformed
        VentanaInterna vi = (VentanaInterna)(escritorio.getSelectedFrame());
        String filtro = (String) comboFiltros.getSelectedItem();
            if (vi != null){
                imgSource = vi.getLienzo().getImage();
                try{
                    Kernel k = null; 
                    switch(filtro){
                        case "Media":
                            k = KernelProducer.createKernel(KernelProducer.TYPE_MEDIA_3x3);
                            break;
                        case "Binomial":
                            k = KernelProducer.createKernel(KernelProducer.TYPE_BINOMIAL_3x3);
                            break;
                        case "Enfoque":
                            k = KernelProducer.createKernel(KernelProducer.TYPE_ENFOQUE_3x3);
                            break; 
                        case "Relieve":
                            k = KernelProducer.createKernel(KernelProducer.TYPE_RELIEVE_3x3);
                            break;
                        case "Fronteras":
                            k = KernelProducer.createKernel(KernelProducer.TYPE_LAPLACIANA_3x3);
                            break;
                    }
                    if (k!=null){
                        ConvolveOp cop = new ConvolveOp(k, ConvolveOp.EDGE_NO_OP, null);
                        BufferedImage img = cop.filter(imgSource, null);
                        vi.getLienzo().setImage(img);
                        vi.getLienzo().repaint();
                    }
                } catch(IllegalArgumentException e){
                    System.err.println("Error");
                }
        }
    }//GEN-LAST:event_comboFiltrosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Abrir;
    private javax.swing.JMenu Archivo;
    private javax.swing.JMenu Edicion;
    private javax.swing.JMenuItem Guardar;
    private javax.swing.JMenu Imagen;
    private javax.swing.JMenuItem Nuevo;
    private javax.swing.JMenuItem RescaleOp;
    private javax.swing.JToggleButton alisar;
    private javax.swing.JToggleButton amarillo;
    private javax.swing.JPanel atributos;
    private javax.swing.JToggleButton azul;
    private javax.swing.JToolBar barraHerramientas;
    private javax.swing.JToggleButton blanco;
    private javax.swing.JPanel brillibrilli;
    private javax.swing.ButtonGroup colores;
    private javax.swing.JPanel colores2;
    private javax.swing.JComboBox<String> comboFiltros;
    private javax.swing.JPanel constrati;
    private javax.swing.JToggleButton elipse;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel etiqueta;
    private javax.swing.JPanel filtrito;
    private javax.swing.JMenuItem filtrosConvolve;
    private javax.swing.ButtonGroup formas;
    private javax.swing.JToolBar herramientasImagenes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToggleButton linea;
    private javax.swing.JToggleButton negro;
    private javax.swing.JToggleButton punto;
    private javax.swing.JToggleButton rectangulo;
    private javax.swing.JToggleButton relleno;
    private javax.swing.JToggleButton rojo;
    private javax.swing.JToggleButton selecion;
    private javax.swing.JSlider sliderBrillo;
    private javax.swing.JSpinner tamGrosor;
    private javax.swing.JToggleButton transparencia;
    private javax.swing.JCheckBoxMenuItem verBarraAtributos;
    private javax.swing.JCheckBoxMenuItem verBarraEstado;
    private javax.swing.JCheckBoxMenuItem verBarraFormas;
    private javax.swing.JToggleButton verde;
    // End of variables declaration//GEN-END:variables
}
