/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import java.awt.image.BufferedImage;
import java.beans.PropertyVetoException;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import uk.co.caprica.vlcj.component.EmbeddedMediaPlayerComponent;
import uk.co.caprica.vlcj.player.MediaPlayerEventListener;
import uk.co.caprica.vlcj.player.embedded.EmbeddedMediaPlayer;

/**
 *
 * @author Paula Ruiz
 */
public class VentanaInternaVLCPlayer extends javax.swing.JInternalFrame {
    private EmbeddedMediaPlayer vlcPlayer = null;
    private File fMedia; 
    /**
     * Creates new form VentanaInternaVLCPlayer
     */
    public VentanaInternaVLCPlayer(File f) {
        initComponents();
        setSize(500,500);
        fMedia = f; 
        EmbeddedMediaPlayerComponent aVisual = new EmbeddedMediaPlayerComponent();
        getContentPane().add(aVisual, java.awt.BorderLayout.CENTER);
        vlcPlayer = aVisual.getMediaPlayer();
        System.out.println("Vamos a reproducirlo");
    }
    
    public static VentanaInternaVLCPlayer getInstance(File f){
        VentanaInternaVLCPlayer v = new VentanaInternaVLCPlayer(f);
        return (v.vlcPlayer!=null?v:null);
    }
    
    public void play() {
        if(vlcPlayer != null){
            if(vlcPlayer.isPlayable()){
                vlcPlayer.play();
            } else {
                vlcPlayer.playMedia(fMedia.getAbsolutePath());
            }
        }
    }
    
    public void stop(){
        if(vlcPlayer != null) {
            if (vlcPlayer.isPlaying()){
                vlcPlayer.pause();
            } else {
                vlcPlayer.stop();
            }
        }
    }
    
    public void addMediaPlayerEventListener(MediaPlayerEventListener ml){
        if(vlcPlayer != null){
            vlcPlayer.addMediaPlayerEventListener(ml);
        }
    }
    
    public BufferedImage getImage(){
        return vlcPlayer.getSnapshot();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        stop();
    }//GEN-LAST:event_formInternalFrameClosing

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        try {
            this.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(VentanaInternaVLCPlayer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
