/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica13_audio;

import java.io.File;
import javax.swing.JFileChooser;
import sm.sound.SMClipPlayer;
import sm.sound.SMPlayer;
import sm.sound.SMRecorder;

/**
 *
 * @author Shiri
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    SMPlayer player = null;
    SMRecorder recorder;
    File f = null; 
    
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        play = new javax.swing.JButton();
        stop = new javax.swing.JButton();
        listaReproduccion = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        grabar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        abrirAudio = new javax.swing.JMenuItem();
        GrabarAudio = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        play.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica13_audio/iconos/play24x24.png"))); // NOI18N
        play.setToolTipText("");
        play.setFocusable(false);
        play.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        play.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playActionPerformed(evt);
            }
        });
        jToolBar1.add(play);

        stop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica13_audio/iconos/pausa24x24.png"))); // NOI18N
        stop.setFocusable(false);
        stop.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        stop.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopActionPerformed(evt);
            }
        });
        jToolBar1.add(stop);

        jToolBar1.add(listaReproduccion);
        jToolBar1.add(jSeparator1);

        grabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica13_audio/iconos/record24x24.png"))); // NOI18N
        grabar.setFocusable(false);
        grabar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        grabar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        grabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grabarActionPerformed(evt);
            }
        });
        jToolBar1.add(grabar);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        jMenu1.setText("File");

        abrirAudio.setText("AbrirAudio");
        abrirAudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirAudioActionPerformed(evt);
            }
        });
        jMenu1.add(abrirAudio);

        GrabarAudio.setText("GrabarAudio");
        GrabarAudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GrabarAudioActionPerformed(evt);
            }
        });
        jMenu1.add(GrabarAudio);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abrirAudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirAudioActionPerformed
        JFileChooser dlg = new JFileChooser();
        int resp = dlg.showOpenDialog(this);
        if( resp == JFileChooser.APPROVE_OPTION) {
            try{
                f = new File(dlg.getSelectedFile().getAbsolutePath()){
                    @Override
                    public String toString(){
                        return this.getName();
                    }
                };
            }catch(Exception ex){
                System.err.println("Error al leer la imagen");
            }
        }
        
        listaReproduccion.addItem(f);
    }//GEN-LAST:event_abrirAudioActionPerformed

    private void GrabarAudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GrabarAudioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GrabarAudioActionPerformed

    private void playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playActionPerformed
        File f = (File)listaReproduccion.getSelectedItem();
        if(f!=null){
            player = new SMClipPlayer(f);
            if (player != null) {
                player.play();
            }
        }
    }//GEN-LAST:event_playActionPerformed

    private void stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopActionPerformed
                player.stop();
    }//GEN-LAST:event_stopActionPerformed

    private void grabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grabarActionPerformed
        JFileChooser dlg = new JFileChooser();
        int resp = dlg.showSaveDialog(this);
        if (resp == JFileChooser.APPROVE_OPTION) {
            try {
                
                if (img != null) {
                    File f = dlg.getSelectedFile();
                    ImageIO.write(img, "jpg", f);
                    vi.setTitle(f.getName());
                }
            }catch (Exception ex) {
                System.err.println("Error al guardar la imagen");
            }
        }
    }//GEN-LAST:event_grabarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem GrabarAudio;
    private javax.swing.JMenuItem abrirAudio;
    private javax.swing.JButton grabar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JComboBox<File> listaReproduccion;
    private javax.swing.JButton play;
    private javax.swing.JButton stop;
    // End of variables declaration//GEN-END:variables
}
