/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica7_paint2d;

import java.awt.BasicStroke;
import java.awt.Stroke;

/**
 *
 * @author Shiri
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form ventanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        colores = new javax.swing.ButtonGroup();
        formas = new javax.swing.ButtonGroup();
        barraAtributos = new javax.swing.JPanel();
        etiqueta = new javax.swing.JLabel();
        atributos = new javax.swing.JPanel();
        panelColores = new javax.swing.JPanel();
        tablaColores = new javax.swing.JPanel();
        colores1 = new javax.swing.JPanel();
        negro = new javax.swing.JToggleButton();
        rojo = new javax.swing.JToggleButton();
        azul = new javax.swing.JToggleButton();
        colores2 = new javax.swing.JPanel();
        blanco = new javax.swing.JToggleButton();
        amarillo = new javax.swing.JToggleButton();
        verde = new javax.swing.JToggleButton();
        color_texto = new java.awt.Label();
        panelGrosor = new javax.swing.JPanel();
        grosor_texto = new java.awt.Label();
        grosor = new javax.swing.JPanel();
        tamGrosor = new javax.swing.JSpinner();
        panelAtributos = new javax.swing.JPanel();
        atributos1 = new javax.swing.JPanel();
        relleno = new javax.swing.JCheckBox();
        alisar = new javax.swing.JCheckBox();
        atributos2 = new javax.swing.JPanel();
        transparencia = new javax.swing.JCheckBox();
        editar = new javax.swing.JCheckBox();
        barraHerramientas = new javax.swing.JToolBar();
        punto = new javax.swing.JToggleButton();
        linea = new javax.swing.JToggleButton();
        rectangulo = new javax.swing.JToggleButton();
        elipse = new javax.swing.JToggleButton();
        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Nuevo = new javax.swing.JMenuItem();
        Abrir = new javax.swing.JMenuItem();
        Guardar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        verBarraEstado = new javax.swing.JCheckBoxMenuItem();
        verBarraFormas = new javax.swing.JCheckBoxMenuItem();
        verBarraAtributos = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        barraAtributos.setLayout(new java.awt.BorderLayout());

        etiqueta.setText("jLabel1");
        barraAtributos.add(etiqueta, java.awt.BorderLayout.PAGE_END);

        atributos.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        panelColores.setLayout(new java.awt.BorderLayout());

        tablaColores.setLayout(new java.awt.BorderLayout());

        negro.setBackground(java.awt.Color.black);
        colores.add(negro);
        negro.setPreferredSize(new java.awt.Dimension(20, 20));
        colores1.add(negro);

        rojo.setBackground(java.awt.Color.red);
        colores.add(rojo);
        rojo.setPreferredSize(new java.awt.Dimension(20, 20));
        colores1.add(rojo);

        azul.setBackground(java.awt.Color.blue);
        colores.add(azul);
        azul.setPreferredSize(new java.awt.Dimension(20, 20));
        colores1.add(azul);

        tablaColores.add(colores1, java.awt.BorderLayout.PAGE_START);

        blanco.setBackground(java.awt.Color.white);
        colores.add(blanco);
        blanco.setPreferredSize(new java.awt.Dimension(20, 20));
        colores2.add(blanco);

        amarillo.setBackground(java.awt.Color.yellow);
        colores.add(amarillo);
        amarillo.setPreferredSize(new java.awt.Dimension(20, 20));
        colores2.add(amarillo);

        verde.setBackground(java.awt.Color.green);
        colores.add(verde);
        verde.setPreferredSize(new java.awt.Dimension(20, 20));
        colores2.add(verde);

        tablaColores.add(colores2, java.awt.BorderLayout.PAGE_END);

        panelColores.add(tablaColores, java.awt.BorderLayout.PAGE_END);

        color_texto.setText("Color");
        panelColores.add(color_texto, java.awt.BorderLayout.PAGE_START);

        atributos.add(panelColores);

        panelGrosor.setLayout(new java.awt.BorderLayout());

        grosor_texto.setText("Grosor");
        panelGrosor.add(grosor_texto, java.awt.BorderLayout.PAGE_START);

        tamGrosor.setPreferredSize(new java.awt.Dimension(39, 30));
        tamGrosor.setValue(1);
        tamGrosor.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tamGrosorStateChanged(evt);
            }
        });
        grosor.add(tamGrosor);

        panelGrosor.add(grosor, java.awt.BorderLayout.CENTER);

        atributos.add(panelGrosor);

        panelAtributos.setLayout(new java.awt.BorderLayout());

        atributos1.setLayout(new java.awt.BorderLayout());

        relleno.setText("Relleno");
        atributos1.add(relleno, java.awt.BorderLayout.PAGE_START);

        alisar.setText("Alisar");
        atributos1.add(alisar, java.awt.BorderLayout.PAGE_END);

        panelAtributos.add(atributos1, java.awt.BorderLayout.LINE_START);

        atributos2.setLayout(new java.awt.BorderLayout());

        transparencia.setText("Transparencia");
        atributos2.add(transparencia, java.awt.BorderLayout.PAGE_START);

        editar.setText("Editar");
        atributos2.add(editar, java.awt.BorderLayout.PAGE_END);

        panelAtributos.add(atributos2, java.awt.BorderLayout.LINE_END);

        atributos.add(panelAtributos);

        barraAtributos.add(atributos, java.awt.BorderLayout.CENTER);

        getContentPane().add(barraAtributos, java.awt.BorderLayout.PAGE_END);

        barraHerramientas.setRollover(true);

        formas.add(punto);
        punto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica7_paint2d/iconos/punto.png"))); // NOI18N
        punto.setFocusable(false);
        punto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        punto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        punto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puntoActionPerformed(evt);
            }
        });
        barraHerramientas.add(punto);

        formas.add(linea);
        linea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica7_paint2d/iconos/linea.png"))); // NOI18N
        linea.setFocusable(false);
        linea.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        linea.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        linea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lineaActionPerformed(evt);
            }
        });
        barraHerramientas.add(linea);

        formas.add(rectangulo);
        rectangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica7_paint2d/iconos/rectangulo.png"))); // NOI18N
        rectangulo.setFocusable(false);
        rectangulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rectangulo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        rectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rectanguloActionPerformed(evt);
            }
        });
        barraHerramientas.add(rectangulo);

        formas.add(elipse);
        elipse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica7_paint2d/iconos/elipse.png"))); // NOI18N
        elipse.setFocusable(false);
        elipse.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        elipse.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        elipse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elipseActionPerformed(evt);
            }
        });
        barraHerramientas.add(elipse);

        getContentPane().add(barraHerramientas, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 142, Short.MAX_VALUE)
        );

        getContentPane().add(escritorio, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");

        Nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica7_paint2d/iconos/nuevo.png"))); // NOI18N
        Nuevo.setText("Nuevo");
        Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoActionPerformed(evt);
            }
        });
        jMenu1.add(Nuevo);

        Abrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica7_paint2d/iconos/abrir.png"))); // NOI18N
        Abrir.setText("Abrir");
        jMenu1.add(Abrir);

        Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica7_paint2d/iconos/guardar.png"))); // NOI18N
        Guardar.setText("Guardar");
        jMenu1.add(Guardar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        verBarraEstado.setSelected(true);
        verBarraEstado.setText("Ver barra de estado");
        jMenu2.add(verBarraEstado);

        verBarraFormas.setSelected(true);
        verBarraFormas.setText("Ver barra de formas");
        jMenu2.add(verBarraFormas);

        verBarraAtributos.setSelected(true);
        verBarraAtributos.setText("Ver barra de atributos");
        jMenu2.add(verBarraAtributos);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoActionPerformed
        VentanaInterna vi = new VentanaInterna();
        escritorio.add(vi);
        vi.setVisible(true);
    }//GEN-LAST:event_NuevoActionPerformed

    private void lineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lineaActionPerformed
        VentanaInterna vi;
        vi = (VentanaInterna)escritorio.getSelectedFrame();
        vi.getLienzo().setForma(Herramientas.linea);
    }//GEN-LAST:event_lineaActionPerformed

    private void rectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rectanguloActionPerformed
        VentanaInterna vi;
        vi = (VentanaInterna)escritorio.getSelectedFrame();
        vi.getLienzo().setForma(Herramientas.rectangulo);
    }//GEN-LAST:event_rectanguloActionPerformed

    private void elipseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elipseActionPerformed
        VentanaInterna vi;
        vi = (VentanaInterna)escritorio.getSelectedFrame();
        vi.getLienzo().setForma(Herramientas.elipse);
    }//GEN-LAST:event_elipseActionPerformed

    private void puntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puntoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puntoActionPerformed

    private void tamGrosorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tamGrosorStateChanged
        VentanaInterna vi;
        vi = (VentanaInterna)escritorio.getSelectedFrame();
        Stroke nuevo = new BasicStroke((int)tamGrosor.getValue()); 
        vi.getLienzo().setStroke(nuevo); 
    }//GEN-LAST:event_tamGrosorStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Abrir;
    private javax.swing.JMenuItem Guardar;
    private javax.swing.JMenuItem Nuevo;
    private javax.swing.JCheckBox alisar;
    private javax.swing.JToggleButton amarillo;
    private javax.swing.JPanel atributos;
    private javax.swing.JPanel atributos1;
    private javax.swing.JPanel atributos2;
    private javax.swing.JToggleButton azul;
    private javax.swing.JPanel barraAtributos;
    private javax.swing.JToolBar barraHerramientas;
    private javax.swing.JToggleButton blanco;
    private java.awt.Label color_texto;
    private javax.swing.ButtonGroup colores;
    private javax.swing.JPanel colores1;
    private javax.swing.JPanel colores2;
    private javax.swing.JCheckBox editar;
    private javax.swing.JToggleButton elipse;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel etiqueta;
    private javax.swing.ButtonGroup formas;
    private javax.swing.JPanel grosor;
    private java.awt.Label grosor_texto;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToggleButton linea;
    private javax.swing.JToggleButton negro;
    private javax.swing.JPanel panelAtributos;
    private javax.swing.JPanel panelColores;
    private javax.swing.JPanel panelGrosor;
    private javax.swing.JToggleButton punto;
    private javax.swing.JToggleButton rectangulo;
    private javax.swing.JCheckBox relleno;
    private javax.swing.JToggleButton rojo;
    private javax.swing.JPanel tablaColores;
    private javax.swing.JSpinner tamGrosor;
    private javax.swing.JCheckBox transparencia;
    private javax.swing.JCheckBoxMenuItem verBarraAtributos;
    private javax.swing.JCheckBoxMenuItem verBarraEstado;
    private javax.swing.JCheckBoxMenuItem verBarraFormas;
    private javax.swing.JToggleButton verde;
    // End of variables declaration//GEN-END:variables
}
