/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica7_paint2d;

/**
 *
 * @author Shiri
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        forma = new javax.swing.ButtonGroup();
        colores = new javax.swing.ButtonGroup();
        herramientas1 = new javax.swing.JToolBar();
        punto = new javax.swing.JToggleButton();
        linea = new javax.swing.JToggleButton();
        rectangulo = new javax.swing.JToggleButton();
        elipse = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        blanco = new javax.swing.JToggleButton();
        amarillo = new javax.swing.JToggleButton();
        verde = new javax.swing.JToggleButton();
        jPanel7 = new javax.swing.JPanel();
        negro = new javax.swing.JToggleButton();
        rojo = new javax.swing.JToggleButton();
        azul = new javax.swing.JToggleButton();
        jPanel4 = new javax.swing.JPanel();
        jSpinner1 = new javax.swing.JSpinner();
        jPanel8 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        nuevo = new javax.swing.JMenuItem();
        abrir = new javax.swing.JMenuItem();
        guardar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        herramientas1.setRollover(true);

        forma.add(punto);
        punto.setIcon(new javax.swing.ImageIcon("C:\\Users\\Shiri\\Documents\\Informatica\\TI\\Tercero\\SMM\\Practicas\\Practica7\\iconos\\punto.png")); // NOI18N
        punto.setFocusable(false);
        punto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        punto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        herramientas1.add(punto);

        forma.add(linea);
        linea.setIcon(new javax.swing.ImageIcon("C:\\Users\\Shiri\\Documents\\Informatica\\TI\\Tercero\\SMM\\Practicas\\Practica7\\iconos\\linea.png")); // NOI18N
        linea.setFocusable(false);
        linea.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        linea.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        linea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lineaActionPerformed(evt);
            }
        });
        herramientas1.add(linea);

        forma.add(rectangulo);
        rectangulo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Shiri\\Documents\\Informatica\\TI\\Tercero\\SMM\\Practicas\\Practica7\\iconos\\rectangulo.png")); // NOI18N
        rectangulo.setFocusable(false);
        rectangulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rectangulo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        herramientas1.add(rectangulo);

        forma.add(elipse);
        elipse.setIcon(new javax.swing.ImageIcon("C:\\Users\\Shiri\\Documents\\Informatica\\TI\\Tercero\\SMM\\Practicas\\Practica7\\iconos\\elipse.png")); // NOI18N
        elipse.setFocusable(false);
        elipse.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        elipse.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        elipse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elipseActionPerformed(evt);
            }
        });
        herramientas1.add(elipse);

        getContentPane().add(herramientas1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, java.awt.BorderLayout.PAGE_END);

        jPanel3.setLayout(new java.awt.BorderLayout());

        blanco.setBackground(java.awt.Color.white);
        colores.add(blanco);
        blanco.setPreferredSize(new java.awt.Dimension(20, 20));
        jPanel6.add(blanco);

        amarillo.setBackground(java.awt.Color.yellow);
        colores.add(amarillo);
        amarillo.setPreferredSize(new java.awt.Dimension(20, 20));
        amarillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amarilloActionPerformed(evt);
            }
        });
        jPanel6.add(amarillo);

        verde.setBackground(java.awt.Color.green);
        colores.add(verde);
        verde.setPreferredSize(new java.awt.Dimension(20, 20));
        verde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verdeActionPerformed(evt);
            }
        });
        jPanel6.add(verde);

        jPanel3.add(jPanel6, java.awt.BorderLayout.PAGE_END);

        negro.setBackground(java.awt.Color.black);
        colores.add(negro);
        negro.setPreferredSize(new java.awt.Dimension(20, 20));
        jPanel7.add(negro);

        rojo.setBackground(java.awt.Color.red);
        colores.add(rojo);
        rojo.setPreferredSize(new java.awt.Dimension(20, 20));
        jPanel7.add(rojo);

        azul.setBackground(java.awt.Color.blue);
        colores.add(azul);
        azul.setPreferredSize(new java.awt.Dimension(20, 20));
        jPanel7.add(azul);

        jPanel3.add(jPanel7, java.awt.BorderLayout.PAGE_START);

        jPanel2.add(jPanel3);

        jPanel4.add(jSpinner1);

        jPanel2.add(jPanel4);

        jPanel8.setPreferredSize(new java.awt.Dimension(200, 100));
        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jCheckBox1.setText("Relleno");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel8.add(jCheckBox1);

        jCheckBox2.setText("Transparencia");
        jPanel8.add(jCheckBox2);

        jCheckBox3.setText("Alisar");
        jPanel8.add(jCheckBox3);

        jCheckBox4.setText("Editar");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });
        jPanel8.add(jCheckBox4);

        jPanel2.add(jPanel8);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);
        getContentPane().add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Archivo");

        nuevo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Shiri\\Documents\\Informatica\\TI\\Tercero\\SMM\\Practicas\\Practica7\\iconos\\nuevo.png")); // NOI18N
        nuevo.setText("Nuevo");
        nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoActionPerformed(evt);
            }
        });
        jMenu1.add(nuevo);

        abrir.setIcon(new javax.swing.ImageIcon("C:\\Users\\Shiri\\Documents\\Informatica\\TI\\Tercero\\SMM\\Practicas\\Practica7\\iconos\\abrir.png")); // NOI18N
        abrir.setText("Abrir");
        jMenu1.add(abrir);

        guardar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Shiri\\Documents\\Informatica\\TI\\Tercero\\SMM\\Practicas\\Practica7\\iconos\\guardar.png")); // NOI18N
        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        jMenu1.add(guardar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edicion");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Ver barra de estado");
        jMenu2.add(jCheckBoxMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void verdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verdeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_verdeActionPerformed

    private void amarilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amarilloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amarilloActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevoActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guardarActionPerformed

    private void elipseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elipseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_elipseActionPerformed

    private void lineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lineaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lineaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem abrir;
    private javax.swing.JToggleButton amarillo;
    private javax.swing.JToggleButton azul;
    private javax.swing.JToggleButton blanco;
    private javax.swing.ButtonGroup colores;
    private javax.swing.JToggleButton elipse;
    private javax.swing.ButtonGroup forma;
    private javax.swing.JMenuItem guardar;
    private javax.swing.JToolBar herramientas1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JToggleButton linea;
    private javax.swing.JToggleButton negro;
    private javax.swing.JMenuItem nuevo;
    private javax.swing.JToggleButton punto;
    private javax.swing.JToggleButton rectangulo;
    private javax.swing.JToggleButton rojo;
    private javax.swing.JToggleButton verde;
    // End of variables declaration//GEN-END:variables
}
